/* soapFileSaverProxy.h
   Generated by gSOAP 2.8.82 for file_saver_service.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapFileSaverProxy_H
#define soapFileSaverProxy_H
#include "soapH.h"

    class SOAP_CMAC FileSaverProxy : public soap {
      public:
        /// Endpoint URL of service 'FileSaverProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in file_saver_service.h, if any
        /// Construct a proxy with new managing context
        FileSaverProxy();
        /// Copy constructor
        FileSaverProxy(const FileSaverProxy& rhs);
        /// Construct proxy given a managing context
        FileSaverProxy(const struct soap&);
        /// Construct proxy given a managing context and endpoint URL
        FileSaverProxy(const struct soap&, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        FileSaverProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        FileSaverProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        FileSaverProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        FileSaverProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context
        virtual ~FileSaverProxy();
        /// Initializer used by constructors
        virtual void FileSaverProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual FileSaverProxy *copy();
        /// Copy assignment
        FileSaverProxy& operator=(const FileSaverProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'saveFile' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int saveFile(const std::wstring& fileName, const xsd__base64Binary& fileData, enum ns__ErrorCode *errorCode) { return this->saveFile(NULL, NULL, fileName, fileData, errorCode); }
        /// Web service synchronous operation 'saveFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int saveFile(const char *soap_endpoint_url, const char *soap_action, const std::wstring& fileName, const xsd__base64Binary& fileData, enum ns__ErrorCode *errorCode) { return this->send_saveFile(soap_endpoint_url, soap_action, fileName, fileData) || this->recv_saveFile(errorCode) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_saveFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_saveFile(const char *soap_endpoint_url, const char *soap_action, const std::wstring& fileName, const xsd__base64Binary& fileData);
        /// Web service asynchronous operation 'recv_saveFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_saveFile(enum ns__ErrorCode *errorCode);
        //
        /// Web service synchronous operation 'loadFile' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int loadFile(const std::wstring& fileName, ns__loadFileResponse *response) { return this->loadFile(NULL, NULL, fileName, response); }
        /// Web service synchronous operation 'loadFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int loadFile(const char *soap_endpoint_url, const char *soap_action, const std::wstring& fileName, ns__loadFileResponse *response) { return this->send_loadFile(soap_endpoint_url, soap_action, fileName) || this->recv_loadFile(response) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_loadFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_loadFile(const char *soap_endpoint_url, const char *soap_action, const std::wstring& fileName);
        /// Web service asynchronous operation 'recv_loadFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_loadFile(ns__loadFileResponse *response);
    };
#endif
